- reportportal_client/service.py
Having a bug with join paths on windows (windows use backslash \ as path separartor, not forward slash /)
Avoided using platform dependent `os.path.join` to work similar on Windows as on Linux. 
Can someone test this PR on Linux before merge?
> Fixed bugs of using report portal client on windows

- reportportal_client/service.py
Previous commit introduced BearerAuth class.  It adds for each request required auth header (call for each request) which is not necessary in the current implementation because token is not changed during session. Moreover, it performs string formatting operation for each request which is slightly slower.
- Move auth header to session scope due to reasons described above.
> Make bearer auth per session instead of per request

- reportportal_client/model/request.py
- reportportal_client/service.py
This implementation relies on requests `files` parameter. It means that `data` parameter can be a file-like object or file content.
There are two mandatory parameters:
- file name of attachment
- file obj or content
The third `mime` argument can be skipped, in this case content type will be `"application/octet-stream"`.
`agent` implementation modules are responsible for closing file descriptors and providing content for attachment or can use the same approach as is.
Testing example from pytest agent:
```python
with open(file_path, "rb") as fh:
attach("Test message",  name=basename(filepath), data=fh, mime="image/jpeg")
```
Or if data collected from anywhere, just pass it:
```python
attach("Output of 'ps aux'", "ps-aux.txt", subprocess.check_output(["ps", "aux"]))
```
__The only thing need …
> Binary attachment support for issue #4

- reportportal_client/errors.py
- reportportal_client/model/response.py
Was:
```
Traceback (most recent call last):
File "err2.py.txt", line 49, in <module>
print(r.id)
File "./client-python/reportportal_client/model/response.py", line 17, in id
return json.loads(self.raw)["id"]
KeyError: 'id'
```
Now:
```
Traceback (most recent call last):
File "err2.py.txt", line 49, in <module>
print(r.id)
File "./client-python/reportportal_client/model/response.py", line 22, in id
raise EntryCreatedError("raw: {0}".format(self.raw))
reportportal_client.errors.EntryCreatedError: raw: {"error_code":4001,"message":"Incorrect Request. [Incorrect value in save log request 'null' in field 'logTime'.]"}
```
But you still need to access `id` property for checking response:
```python
r = service.log(log_rq)
print(r.id)
```
> Improve error message for part 1 issue #10

- reportportal_client/service.py
- reportportal_client/service_async.py
Add is_skipped_an_issue flag to services to allow uploading skipped
tests items as not 'To Investigate' items on Server side.
> Add flag to allow marking skipped as not 'To Investigate' items

- reportportal_client/__init__.py
- reportportal_client/service.py
addresses #39 
Add a simple retry loop to catch intermittent race condition occurring when py.test unsets `PYTEST_CURRENT_TEST` variable during `urllib`'s iterating over env. variables
> Retry POSTing logs if KeyError occurs on iterating over env variables

- reportportal_client/service.py
Sorry, i noticed this too late, but the module variable import at the beginning of the `service.py` module was causing a circular depenency error on importing the whole module.
The solution to this is import the variable later in the code.
```python
In [1]: import reportportal_client
In [2]: reportportal_client.POST_LOGBATCH_RETRY_COUNT
Out[2]: 10
In [3]: from reportportal_client import POST_LOGBATCH_RETRY_COUNT
In [4]: POST_LOGBATCH_RETRY_COUNT
Out[4]: 10
```
> fix the circular dependency regression on importing POST_LOGBATCH_RETRY_COUNT

- setup.py
This is for https://github.com/reportportal/client-Python/issues/50.
We have to change the version number for the package to upload it to PyPi without issues. The current package at PyPi contains outdated code.
Once this PR is merged, someone who has access to the reportportal-project at PyPi should complete the following steps:
1. Clone repository
Run from the root of the cloned repo:
2. python setup.py sdist
3. twine upload dist/*
> Bump the version up for uploading to PyPi

- reportportal_client/service.py
- reportportal_client/service_async.py
Adding support for API call: `PUT /{projectName}/item/{item}/update`
Model: 
```
UpdateTestItemRQ {
description (string, optional),
tags (Array[string], optional)
}
```
> Adding support for update test item API call

- reportportal_client/service.py
- tests/test_service.py
> Remove duplicate agent name returned by the get_system_information()

- reportportal_client/__init__.py
- reportportal_client/service.py
https://github.com/reportportal/client-Python/issues/94
After testing going to provide this fix in base master (possible it will be better to create a separate PR)
> Avoid raise condition in os.environ dict (TESTING IN PROGRESS)

- reportportal_client/service.py
- requirements.txt
- setup.py
- tests/test_service.py
1. Moved requirements into a separate file, since some code scan tools (E.g. fossa.com) don't have idea about different requirements declaration methods. Well, actually this point is discussable.
2. Added 'codeRef' parameter bypass and some unit-tests
> Code reference bypass

- requirements.txt
reportportal-client 5.0.5 makes use of Mapping from six.moves.collections_ab for which six >= 1.13.0 is required
Older versions would cause 
<pre><code>
Traceback (most recent call last):
File "test.py", line 3, in <module>
from reportportal_client import ReportPortalService
File "/Users/gbonetti/projects/rp-wrong-version/venv/lib/python3.7/site-packages/reportportal_client/__init__.py", line 17, in <module>
from .service import ReportPortalService
File "/Users/gbonetti/projects/rp-wrong-version/venv/lib/python3.7/site-packages/reportportal_client/service.py", line 25, in <module>
from six.moves.collections_abc import Mapping
ModuleNotFoundError: No module named 'six.moves.collections_abc'
</code></pre>
> Set correct requirement for six >= 1.13.0

- reportportal_client/service.py
- tests/test_service.py
I'm not sure about name `def get_launch_info(self)`. Should I use `def get_launch_by_uuid(self)`?
The unit test also checks that session.get() has been called with the right attributes.
Implement #121
> Method of ReportPortalService to get launch UI URL.

- reportportal_client/service.py
- tests/test_service.py
ReportPortal now supports a functionality through the API which makes rerunning tests possible. This makes the client support it.
Covers issues #107 and #108.
> Add parameters for rerun in `start_launch`

- reportportal_client/errors.py
- reportportal_client/service.py
- tests/test_service.py
Hello, 
Improved `get_launch_info()` a little bit. Could you please let me know what do you think?
1. added the simple polling by result code 200.  
It is ok implementation? It is simple but it works. :)
2. Now it is necessary to check that launch_is is None. Without that, it would request information for ID "None" multiple times. I had to launch something so that I have added a new exception  `LaunchExistsError`. 
Is it an ok name?
3.  Should I add more debug logs like "Retry 1/5"? 
Please review, if this approach is ok, I`ll add few more unit tests to cover retries.
Implements #121.
> Implement a simple polling for get_launch_info(). 

- requirements.txt
collections_abc was added to six in 1.15 and is in use by this package but was not covered prior. Centos 8 includes six.py 1.13 causing an error
> Bump six requirement

- reportportal_client/service.py
this is required by https://github.com/reportportal/agent-python-pytest/pull/240
It sets the `self.launch_id` according `kwargs['launch_id']` if provided (otherwise it sets it to `None` just as before. The change is non-breaking.
> use provided launch_id if passed via kwargs

- requirements.txt
enum34 is only compatible with python 3.3 and earlier.
Installing enum34 in a python 3.4+ venv has the potential to cause `AttributeError` for other libraries when this package is installed.
The enum imports present in the package should all work fine with the built-in enum available in python 3.4+
Example of the AttributeError observed in py38 environment when enum34==1.1.10 is installed:
```
Collecting airgun
Cloning https://github.com/SatelliteQE/airgun.git (to revision master) to /tmp/pip-install-crkp_58y/airgun_4a0d43fe511d4f739bbb9a29fae348e6
Installing build dependencies ... error
ERROR: Command errored out with exit status 1:
command: /home/setup/repos/robottelo/.robottelo/bin/python3.8 /home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/pip install …
```
> Restrict enum34 dependency to python 3.3 or earlier

- reportportal_client/service.py
See https://github.com/reportportal/client-Python/issues/155 for more details.
This issue was found when envoy was put as a sidecar for RP's api service since
envoy doesn't accept tokens with 'bearer'.
> Bearer word in Bearer tokens is case sensitive so fixing it.

- reportportal_client/service.py
- requirements.txt
- tests/test_service.py
This is required by a [retry](https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/retries.md#retries-reporting) workflow
> parse optional retry parameter when starting a new child test item

- reportportal_client/logs/__init__.py
Don't fail on missing 'attachment' attributre in RPLogHandler
> Fixes #184

- reportportal_client/core/worker.py
These camelCase aliases were deprecated in Python 3.10 (October 2021).
Replace with the snake_case versions, added in Python 2.6 (October 2008).
* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/pull/25174
> Replace deprecated threading aliases

- reportportal_client/client.py
- reportportal_client/service.py
> Allow setting `HTTPAdapter.pool_maxsize` without `retries`

- reportportal_client/client.py
It looks like this was missed and it resulted in some errors while trying to interact with an instance that was using a self-signed certificate.
> pass verify_ssl parameter also to LogManager instance

- reportportal_client/aio/client.py
I have a tool that (reliably) uploads test results to our RP instance.
We recently added https certifacates to our servers.
But trying to use `verify_ssl='C:/GIT/MyProject/myCert.crt'` with the ASYNC_THREAD client resulted in the following error:
```python
ReportPortal None request failed
Traceback (most recent call last):
File "C:\Users\xxx\Desktop\Python3\Python311\Lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\xxx\Desktop\Python3\Python311\Lib\asyncio\base_events.py", line 1113, in create_connection
transport, protocol = await self._create_connection_transport(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fix ssl context when certificate is provided

- reportportal_client/logs/__init__.py
- tests/logs/test_rp_logger.py
Fixes #234 
adding file location assertion to test_rp_logger, and fixing for 3.11
> Fixing Record pathnames are incorrect on python3.11

- setup.py
The license id has an unusual '.' prefix on it. I've dropped that, but also switched it to the official "Apache-2.0" SPDX ID while I'm at it.
> Fixing the license id
